modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL=""
license="All rights reserved"

[[mods]]
    modId="pokecube_compat"
    version="${file.jarVersion}"
    displayName="Pokécube Mod Compat Module"
    authors="Thutmose"
    description='''
    Extra Cross-Mod Compatiblity for Pokécube
    '''
    
[[dependencies.pokecube_compat]]
    modId="minecraft"
    mandatory=true
    versionRange="version_mc"
    ordering="NONE"
    side="BOTH"
[[dependencies.pokecube_compat]]
    modId="pokecube"
    mandatory=true
    versionRange="version_pokecube"
    ordering="NONE"
    side="BOTH"